flask_app/movies/routes.py
from flask import Blueprint, render_template, url_for, redirect, request, flash
from flask_login import current_user

from .. import movie_client
from ..forms import MovieReviewForm, SearchForm, SearchUserForm
from ..models import User, Review
from ..utils import current_time


movies = Blueprint('movies',__name__)
main = Blueprint('main', __name__)

@movies.route("/users", methods=["GET", "POST"])
def search_users():
    form = SearchUserForm()
    print("HERE0")
    if form.validate_on_submit():
        print("HERE1")
        return redirect(url_for("movies.query_users", query=form.query.data))
    print()
    return render_template("searchUser.html", form=form)

@movies.route("/users/search-results/<query>", methods=["GET"])
def query_users(query):
    try:
        print("HERE2")
        results = User.objects(username=query).first()
    except ValueError as e:
        flash(str(e))
        return redirect(url_for("movies.search_users"))

    return render_template("userQuery.html", results=results)

@movies.route("/user/<username>")
def user_detail(username):
    user = User.objects(username=username).first()
    reviews = Review.objects(commenter=user)

    return render_template("user_detail.html", username=username, reviews=reviews)

@movies.route("/", methods=["GET", "POST"])
def index():
    form = SearchForm()

    if form.validate_on_submit():
        return redirect(url_for("movies.query_results", query=form.search_query.data))

    return render_template("index.html", form=form)


@movies.route("/search-results/<query>", methods=["GET"])
def query_results(query):
    try:
        results = movie_client.search(query)
    except ValueError as e:
        flash(str(e))
        return redirect(url_for("movies.index"))

    return render_template("query.html", results=results)


@movies.route("/movies/<movie_id>", methods=["GET", "POST"])
def movie_detail(movie_id):
    try:
        result = movie_client.retrieve_movie_by_id(movie_id)
    except ValueError as e:
        flash(str(e))
        return redirect(url_for("movies.index"))

    form = MovieReviewForm()
    if form.validate_on_submit() and current_user.is_authenticated:
        review = Review(
            commenter=current_user._get_current_object(),
            content=form.text.data,
            date=current_time(),
            imdb_id=movie_id,
            movie_title=result.title,
            reviewerType=current_user._get_current_object().accountType,
            score = form.score.data

        )

        review.save()

        return redirect(request.path)

    
    """
        Check if the person is critic or normal then change that list by adding the new score
        result.normalScore.apped(form.score.data)
        """

    reviews = Review.objects(imdb_id=movie_id)

    scoreList = []
    for curr in reviews:
        scoreList.append(curr.score)
    

        if (current_user._get_current_object().accountType == "Terp Critic"):
            
            result.updateTerpScore(curr.score)
                
        elif (current_user._get_current_object().accountType == "Normal Critic"):
            result.updateNormalpScore(curr.score)

    
    print("this is the list: " + str(result.terpScores))
    return render_template(
        "movie_detail.html", form=form, movie=result, reviews=reviews)

flask_app/users/routes.py
from flask import Blueprint, redirect, url_for, render_template, flash, request
from flask_login import current_user, login_required, login_user, logout_user

from .. import bcrypt
from ..forms import RegistrationForm, LoginForm, UpdateUsernameForm
from ..models import User


users = Blueprint('users',__name__)

@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user = User(username=form.username.data, email=form.email.data, password=hashed,accountType = form.accountType.data)
        user.save()

        return redirect(url_for("users.login"))

    return render_template("register.html", title="Register", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("movies.index"))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.objects(username=form.username.data).first()

        if user is not None and bcrypt.check_password_hash(
            user.password, form.password.data
        ):
            login_user(user)
            return redirect(url_for("users.account"))
        else:
            flash("Login failed. Check your username and/or password")
            return redirect(url_for("users.login"))

    return render_template("login.html", title="Login", form=form)


@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("movies.index"))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    username_form = UpdateUsernameForm()

    if username_form.validate_on_submit():
        current_user.modify(username=username_form.username.data)
        current_user.save()
        return redirect(url_for("users.account"))

    return render_template("account.html",title="Account",username_form=username_form,
    )

flask_app/templates/account.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <h1>Hey, {{ current_user.username }}!</h1>
    </div>
</div>
<div class="row">
    <div class="col">
        <form action="" method="post">
            {{ username_form.csrf_token }}
            <div class="form-group">
                {{ username_form.username.label(class="form-control-label") }}
                {{ username_form.username(class="form-control form-control-lg") }}

                {% if username_form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in username_form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ username_form.submit }}
            </div>
        </form>
    </div>
</div>
<a href="{{ url_for('movies.user_detail', username=current_user.username) }}">
    <h4>Click here to see all of your posts and comments!</h4>
</a>
{% endblock %}>

flask_app/templates/base.html
<html lang="en">
<head>
    <p style="background-image: url('img_girl.jpg');">


    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
     <link rel="stylesheet" href="{{ url_for('static', filename='custom.css') }}">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Terp Tomatoes</title>
    {% endif %}
</head>

<body>
   
    {% block header %}
    <h1>Overrideable Content</h1>
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

flask_app/templates/header.html
{% extends "base.html" %}
{% block header %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{{ url_for('movies.index') }}">Terp Tomatoes!</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('movies.search_users')}}">
                    Search user
                </a>
            </li>
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.account') }}">
                    Account
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.logout') }}">
                    Logout
                </a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.login') }}">
                    Login
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.register') }}">
                    Register
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>


<div class="container">
    {% block content %}{% endblock %}
</div>
{% endblock %}

flask_app/templates/index.html
{% extends "header.html" %}
{% block content %}

<div class="row">
    <div class="col">
        <form action="/" class="form-inline my-2 my-lg-0" method="POST">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-info">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            {{ form.csrf_token }}
            {{ form.search_query(class="form-control", placeholder="Search") }}

            {% if form.search_query.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.search_query.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}

            {{ form.submit(class="btn btn-outline-success") }}
        </form>
        <h2>Welcome! Your reviews will help many other movie lovers find out the ratings of their favorite movies! </h2>
    </div>
        
        <div>
            <img src="https://www.kuhnphoto.net/img-get/I0000gPLtfmzMDYw/s/500/400/1R42-014x.jpg">
        </div>
        <div>
            <img src="https://i.pinimg.com/originals/64/cc/68/64cc681d1f97b4a19879203f1ae697e1.jpg">
        </div>
</div>
{% endblock %}

flask_app/templates/login.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <h2>Log In</h2>
    </div>
</div>
<div class="row">
    <div class="col">
        If you <b>don't</b> have an account, then <a href="{{ url_for('users.register') }}">Register!</a> And start leaving some reviews!
    </div>
</div>
<div class="row">
    <div class="col">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-info">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        <form action="" method="post">
            {{ form.csrf_token }}
            <div class="form-group">
                {{ form.username.label(class="form-control-label green-text") }}
                {{ form.username(class="form-control form-control-md") }}

                {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {{ form.password(class="form-control form-control-lg") }}

                {% if form.password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class="form-control form-control-lg") }}
            </div>
        </form>
    </div>
</div>
{% endblock %}

flask_app/templates/movie_detail.html
{% extends "header.html" %}
{% block content %}

{% if error_msg %}
<b>{{ error_msg }}</b>
{% endif %}

{% if movie %}

{# Display card for the movie details #}
<div class="row">
  <div class="col">
    <div class="card text-center">
      <div class="card-header">
        {{ movie.title }} ({{ movie.year }})
      </div>
      <div class="card-body">
        <img src="{{ movie.poster_url }}" class="mr-3 movie" alt="alt text">
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><b>Directed by:</b> {{ movie.director }}</li>
          <li class="list-group-item"><b>Actors:</b> {{ movie.actors }}</li>
          <li class="list-group-item"><b>Genres:</b> {{ movie.genres }}</li>
          <li class="list-group-item"><b>Awards:</b> {{ movie.awards }}</li>
          <li class="list-group-item"><b> Terp Rating Score: </b> {{ movie.terpMean }}</li>
          <li class="list-group-item"><b> Normal Rating Score: </b> {{ movie.normalMean }}</li>
        </ul>
      </div>
    </div>
  </div>
</div>

{# Reviews #}
<div class="row">
  <div class="col-md-12">
    <h1> Reviews <small class="float-right">{{ reviews|length }} reviews</small></h1>
    <ul class="media-list">
      {% for review in reviews %}
      <li class="media review-item">
        <div class="media-body">
          <span class="float-right">
            <small>{{ review.date }}</small>
          </span>
          <a href="{{ url_for('movies.user_detail', username=review.commenter.username) }}">
            <strong>@{{ review.commenter.username }}</strong>
          </a>

          <style>
            .tab {
              display: inline-block;
              margin-left: 40px;
            }
          </style>

          {% if review.reviewerType == 'Terp Critic'%}
          <b style="color: red">({{review.reviewerType}})</b>
          {% else %}
          <b style="color: green">({{review.reviewerType}})</b>
          {% endif %}


          <span class="tab"></span>
        

          <strong> Score: {{review.score}}/5 </strong>
          <p>
            {{ review.content }}
          </p>
        </div>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>

{% if current_user.is_authenticated %}
{# Movie review submission form #}
<div class="row">
  <div class="col">
    <form method="POST" action="">
      {{ form.csrf_token }}

      <div class="form-group">
        {{ form.text.label }}
        {{ form.text(class="form-control") }}

        {% if form.text.errors %}
        <div class="alert alert-warning" role="alert">
          {% for error in form.text.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% endif %}

      </div>


      <div class="form-group">
        {{ form.score.label }}
        {{ form.score(class="form-control") }}
      
        {% if form.score.errors %}
        <div class="alert alert-warning" role="alert">
          {% for error in form.score.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% endif %}
      
      </div>



      {{ form.submit() }}
    </form>
  </div>
</div>
{% endif %}
{% endif %}
{% endblock content %}

flask_app/templates/query.html
{% extends "header.html" %}
{% block content %}
{% if error_msg %}
    <p>{{ error_msg }}</p>
{% endif %}

<div class="container-fluid">
    {% for result in results %}
    <div class="media">
        <img src="{{ result.poster_url }}" class="mr-3 movie" alt="missing">
        <div class="media-body">
        <h5 class="mt-0"><a href="{{ url_for('movies.movie_detail', movie_id=result.imdb_id) }}">{{ result.title }}</a> ({{ result.year }})</h5>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

flask_app/templates/register.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <h2>Registration</h2>
    </div>
</div>
<div class="row">
    <div class="col">
        If you already have an account, then just <a href="{{ url_for('users.login') }}">Log In!</a>
    </div>
</div>
<!-- Registration Form: -->
<div class="row">
    <div class="col">
        <form action="" method="post">
            {{ form.csrf_token }}
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                {{ form.username(class="form-control form-control-lg") }}
                {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>


            <div class="form-group">
                {{ form.accountType.label(class="form-control-label") }}
                {{ form.accountType(class="form-control form-control-lg") }}
                {% if form.accountType.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.accountType.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>


            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {{ form.email(class="form-control form-control-lg") }}
                {% if form.email.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>


            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {{ form.password(class="form-control form-control-lg") }}
                {% if form.password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {{ form.confirm_password(class="form-control form-control-lg") }}
                {% if form.confirm_password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class="form-control form-control-lg") }}
            </div>
        </form>
    </div>
</div>

{% endblock %}

flask_app/templates/searchUser.html
{% extends "header.html" %}
{% block content %}

<div class="row">
    <div class="col">
        <form action="/users" class="form-inline my-2 my-lg-0" method="POST">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-info">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            {{ form.csrf_token }}
            {{ form.query(class="form-control", placeholder="Search") }}

            {% if form.query.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.query.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}

            {{ form.submit(class="btn btn-outline-success") }}
        </form>
        <h2>Search for a user</h2>
    </div>

    {%endblock%}

flask_app/templates/userQuery.html
{% extends "header.html" %}
{% block content %}
{% if error_msg %}
    <p>{{ error_msg }}</p>
{% endif %}

<div class="container-fluid">
    <h1>User Result:</h1>
    {% if results %}
    <div>
        <h2><a href="{{url_for("movies.user_detail", username=results.username) }}">{{results.username}}</a></h2>
    </div>
    {% else %}
    <p> Sorry, no users match that name</p>
    {% endif %}
</div>

{% endblock %}

flask_app/templates/user_detail.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <img class="propic" src="data:image/png;base64,{{image}}" alt="image">
    </div>
    <div class="col">
        <h2>{{ username }}'s Reviews</h2>
    </div>
</div>
<div class="row">
    <div class="col">
        <h1> Reviews <small class="float-right">{{ reviews.count() }} reviews</small></h1>
        <ul class="media-list">
            {% for review in reviews %}
            <li class="media review-item">
                <div class="media-body">
                    <span class="float-right">
                        <small>{{ review.date }}</small>
                    </span>
                    <strong>For: <a href="{{ url_for('movies.movie_detail', movie_id=review.imdb_id) }}">
                            {{ review.movie_title }}
                        </a>
                    </strong>
                    <p>
                        {{ review.content }}
                    </p>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}